let
    Source = Folder.Files("E:\Jobs\da_case_study_01\data_copy"),
    #"Removed Other Columns" = Table.SelectColumns(Source,{"Content", "Name"}),
    #"Added Custom" = Table.AddColumn(#"Removed Other Columns", "Custom", each Excel.Workbook([Content])),
    #"Removed Other Columns1" = Table.SelectColumns(#"Added Custom",{"Name", "Custom"}),
    #"Expanded Custom" = Table.ExpandTableColumn(#"Removed Other Columns1", "Custom", {"Data"}, {"Data"}),
    #"Added Custom1" = Table.AddColumn(#"Expanded Custom", "Custom", each Table.PromoteHeaders([Data])),
    #"Removed Other Columns2" = Table.SelectColumns(#"Added Custom1",{"Name", "Custom"}),
    #"Expanded Custom1" = Table.ExpandTableColumn(#"Removed Other Columns2", "Custom", {"ride_id", "rideable_type", "started_at", "ended_at", "start_station_name", "start_station_id", "end_station_name", "end_station_id", "start_lat", "start_lng", "end_lat", "end_lng", "member_casual"}, {"ride_id", "rideable_type", "started_at", "ended_at", "start_station_name", "start_station_id", "end_station_name", "end_station_id", "start_lat", "start_lng", "end_lat", "end_lng", "member_casual"}),
    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Custom1",{{"started_at", type datetime}, {"ended_at", type datetime}}),
    #"Added Custom2" = Table.AddColumn(#"Changed Type", "ride_length", each [ended_at]-[started_at]),
    #"Calculated Total Minutes" = Table.TransformColumns(#"Added Custom2",{{"ride_length", Duration.TotalMinutes, type number}}),

// Filtered out rows that did not have a starting station id OR end station id
    #"Filtered Rows" = Table.SelectRows(#"Calculated Total Minutes", each [start_station_id] <> null and [start_station_id] <> ""),
    #"Filtered Rows1" = Table.SelectRows(#"Filtered Rows", each [end_station_id] <> null and [end_station_id] <> "")
in
    #"Filtered Rows1"
